import { test, expect } from '@playwright/test';
import { randomUUID, randomBytes, createHash } from 'node:crypto';
import { createDatabase } from '../../packages/db/src/index';
const url=process.env.TEST_DATABASE_URL;
if(!url||!new URL(url).pathname.endsWith('_test'))throw new Error('Dedicated test database required');
const database=createDatabase(url);
test.afterAll(()=>database.close());
test('notifications persist read state and enforce recipient, role and CSRF boundaries',async({page,context,baseURL},testInfo)=>{
  const owner=randomUUID(),tenant=randomUUID(),notice=randomUUID(),token=randomBytes(32).toString('base64url');
  await database.client`insert into users(id,email,password_hash,name,email_verified_at) values(${owner},${`notifications-${owner}@example.test`},'unusable','Notifications browser',now())`;
  await database.client`insert into organizations(id,name) values(${tenant},'Notifications browser')`;
  await database.client`insert into organization_members(tenant_id,user_id,role) values(${tenant},${owner},'OWNER')`;
  await database.client`insert into sessions(user_id,token_hash,expires_at) values(${owner},${createHash('sha256').update(token).digest('hex')},now()+interval '1 hour')`;
  await database.client`insert into notifications(id,tenant_id,user_id,source_key,type,audience,resource_id) values(${notice},${tenant},${owner},${`browser:${notice}`},'PAYMENT_SUCCESS','OWNERS',${randomUUID()})`;
  await context.addCookies([{name:'contentos_session',value:token,url:baseURL!,httpOnly:true,sameSite:'Lax'}]);
  const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto(`/notifications?organization=${tenant}`);
  await expect(page.getByRole('heading',{name:'Оплата подтверждена'})).toBeVisible();
  await expect(page.getByText('Непрочитано: 1',{exact:true})).toBeVisible();
  await expect(page.getByRole('link',{name:'Открыть',exact:true})).toHaveAttribute('href',`/billing?organization=${tenant}`);
  await page.screenshot({path:testInfo.outputPath('notifications-desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  await page.screenshot({path:testInfo.outputPath('notifications-mobile.png'),fullPage:true});
  const endpoint=`/api/organizations/${tenant}/notifications`;
  expect((await page.request.post(`${endpoint}/read`,{data:{id:notice}})).status()).toBe(403);
  expect((await page.request.get(`/api/organizations/${randomUUID()}/notifications`)).status()).toBe(404);
  await page.getByRole('button',{name:'Отметить прочитанным'}).click();
  await expect(page.getByText('Непрочитано: 0',{exact:true})).toBeVisible();
  await page.reload();await expect(page.getByText('Прочитано',{exact:true})).toBeVisible();
  await database.client`update organization_members set role='VIEWER' where tenant_id=${tenant} and user_id=${owner}`;
  await page.reload();await expect(page.getByRole('heading',{name:'Пока нет уведомлений'})).toBeVisible();
  expect(errors).toEqual([]);
});
