import { test, expect } from '@playwright/test';
import { randomUUID } from 'node:crypto';
import sharp from 'sharp';
test('register, verify email, create organization and resume 15-step onboarding', async ({ page, request }) => {
  test.setTimeout(420_000); // Includes the scheduled send and persisted analytics round-trip.
  const email = `browser-${randomUUID()}@example.test`;
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/register');
  await page.getByLabel('Ваше имя').fill('Тестовый редактор');
  await page.getByLabel('Электронная почта').fill(email);
  await page.getByLabel('Пароль', { exact: true }).fill('secure-test-password');
  await page.getByRole('button', { name: 'Создать аккаунт' }).click();
  await expect(page.getByRole('status')).toContainText('письмо',{timeout:60000}); // scrypt can exceed 30s on a memory-constrained local machine.
  const response = await request.get(`http://127.0.0.1:8026/?recipient=${encodeURIComponent(email)}`);
  const messages = await response.json() as Array<{ text: string }>;
  const token = messages.at(-1)?.text.match(/token=([a-zA-Z0-9_-]+)/)?.[1];
  expect(token).toBeTruthy();
  await page.goto(`/verify#token=${token}`);
  await page.getByRole('button', { name: 'Подтвердить почту' }).click();
  await expect(page.getByRole('status')).toContainText('Почта подтверждена');
  await page.getByRole('link', { name: 'Войти в аккаунт' }).click();
  await page.getByLabel('Электронная почта').fill(email);
  await page.getByLabel('Пароль', { exact: true }).fill('secure-test-password');
  await page.getByRole('button', { name: 'Войти в пространство' }).click();
  await expect(page.getByRole('heading', { name: 'Всё начинается с бренда' })).toBeVisible({timeout:60000});
  await page.getByLabel('Название организации').fill('Демо-организация');
  await page.getByRole('button', { name: 'Создать организацию', exact: true }).click();
  await page.getByRole('button', { name: 'Добавить бренд', exact: true }).click();
  await page.getByLabel('Название бренда').fill('Студия Север');
  await page.getByRole('button', { name: 'Перейти к настройке' }).click();
  await expect(page.getByRole('heading', { name: 'Как называется ваш бренд?' })).toBeVisible();
  await page.getByRole('button', { name: 'Продолжить', exact: true }).click();
  await page.getByLabel('Сайт компании', { exact: true }).fill('https://example.test');
  await page.getByRole('button', { name: 'Продолжить', exact: true }).click();
  await page.getByLabel('Сфера бизнеса', { exact: true }).fill('Дизайн жилых пространств');
  await page.getByRole('button', { name: 'Сохранить', exact: true }).click();
  await expect(page.getByRole('status')).toHaveText('Изменения сохранены');
  await page.reload();
  await expect(page.getByLabel('Сфера бизнеса', { exact: true })).toHaveValue('Дизайн жилых пространств');
  await page.getByRole('button', { name: 'Продолжить', exact: true }).click();
  const fields = [
    ['География', 'Россия, онлайн'], ['Продукты и услуги', 'Дизайн-проект | Проектирование квартир'],
    ['Целевая аудитория', 'Владельцы квартир | Планируют ремонт'], ['Проблемы аудитории', 'Сложный выбор | Не хватает времени'],
    ['Конкуренты', 'Другая студия | Дизайн интерьеров'], ['Позиционирование', 'Прозрачные этапы и сроки'],
    ['Tone of voice', 'Спокойно, понятно, профессионально'], ['Цели продвижения', 'Повышение доверия\nЗаявки'],
  ];
  for (const [label, value] of fields) {
    await page.getByLabel(label!, { exact: true }).fill(value!);
    await page.getByRole('button', { name: 'Продолжить', exact: true }).click();
  }
  await page.getByLabel('TELEGRAM', { exact: true }).check();
  await page.getByRole('button', { name: 'Продолжить', exact: true }).click();
  await page.getByLabel('Призывы к действию', { exact: true }).fill('Консультация | Записаться на сайте');
  await page.getByRole('button', { name: 'Продолжить', exact: true }).click();
  await page.getByLabel('Лид-магниты', { exact: true }).fill('Чек-лист | Подготовка к ремонту');
  await page.getByRole('button', { name: 'Продолжить', exact: true }).click();
  await page.getByLabel('Ваши примеры', { exact: true }).fill('Пример поста | Как выбрать планировку');
  await page.getByRole('button', { name: 'Создать Brand Brain' }).click();
  await expect(page.getByRole('heading', { name: 'Brand Brain: Студия Север' })).toBeVisible();
  await expect(page.getByText('Дизайн-проект | Проектирование квартир', { exact: true })).toBeVisible();
  await page.getByRole('link', { name: 'В рабочее пространство' }).click();
  await expect(page.getByText('Brand Brain готов', { exact: true })).toBeVisible();
  await page.screenshot({ path: 'test-results/dashboard-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.getByRole('button', { name: 'Добавить бренд', exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/dashboard-mobile.png', fullPage: true });
  await page.getByRole('link').filter({hasText:'Студия Север'}).click();
  await expect(page.getByText('ДЕМО-РЕЖИМ:',{exact:false})).toBeVisible();
  await page.getByRole('button',{name:'Получить стартовые кредиты'}).click();
  await expect(page.getByText('100 AI-кредитов',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Создать стратегию',exact:false}).click();
  await expect(page.getByText('Готово',{exact:true})).toBeVisible({timeout:45000});
  await page.getByRole('button',{name:'Открыть результат',exact:true}).click();
  await expect(page.getByRole('heading',{name:'План на 30 дней'})).toBeVisible();
  await expect(page.getByText('90 AI-кредитов',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Идеи',exact:true}).click();
  await page.getByRole('button',{name:'Сгенерировать идеи',exact:false}).click();
  await expect(page.getByText('Готово',{exact:true})).toHaveCount(2,{timeout:45000});
  await page.getByRole('button',{name:'Идеи',exact:true}).click();
  await expect(page.getByRole('button',{name:'Создать сценарий',exact:false})).toHaveCount(5);
  await page.getByRole('button',{name:'Создать сценарий',exact:false}).first().click();
  await expect(page.getByText('Готово',{exact:true})).toHaveCount(3,{timeout:45000});
  await page.getByRole('button',{name:'Открыть результат',exact:true}).first().click();
  await expect(page.getByLabel('HOOK',{exact:true})).toBeVisible();
  await page.getByLabel('HOOK',{exact:true}).fill('Мой проверенный заголовок');
  await page.getByRole('button',{name:'Сохранить новую версию'}).click();
  await expect(page.getByRole('heading',{name:'Версия 2',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Одобрить сценарий'}).click();
  await expect(page.getByRole('heading',{name:'Версия 2 · Одобрена',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'История версий'}).click();
  await expect(page.getByText('Версия 1',{exact:true})).toBeVisible();
  await expect(page.getByText('85 AI-кредитов',{exact:true})).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  await page.screenshot({path:'test-results/content-mobile.png',fullPage:true});
  await page.setViewportSize({width:1440,height:1000});
  await page.screenshot({path:'test-results/content-desktop.png',fullPage:true});
  await page.getByRole('button',{name:'Согласия',exact:true}).click();
  await page.getByLabel('Имя субъекта',{exact:true}).fill('Вымышленный представитель');
  await page.getByRole('button',{name:'Добавить субъекта',exact:true}).click();
  await page.getByLabel('Я прочитал(а) текст и явно подтверждаю это разрешение',{exact:true}).check();
  await page.getByRole('button',{name:'Сохранить согласие',exact:true}).click();
  await expect(page.getByText('Действует',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Отозвать согласие',exact:true}).click();
  await expect(page.getByText('Отозвано',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Медиа',exact:true}).click();
  const photo=await sharp({create:{width:320,height:480,channels:3,background:'#7bbaa7'}}).png().toBuffer();
  await page.getByLabel('Фотография',{exact:true}).setInputFiles({name:'Тестовая фотография.png',mimeType:'image/png',buffer:photo});
  await page.getByRole('button',{name:'Загрузить фотографию',exact:true}).click();
  await expect(page.getByRole('status')).toHaveText('Фотография сохранена');
  await page.getByRole('button',{name:'Открыть фотографию',exact:true}).click();
  const preview=page.getByRole('img',{name:'Предпросмотр: Тестовая фотография.png',exact:true});
  await expect(preview).toBeVisible();
  await expect.poll(()=>preview.evaluate(image=>(image as HTMLImageElement).naturalWidth)).toBe(320);
  await page.screenshot({path:'test-results/media-desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  await page.screenshot({path:'test-results/media-mobile.png',fullPage:true});
  await page.getByRole('button',{name:'Согласия',exact:true}).click();
  for(const type of ['OWN_LIKENESS','CROSS_BORDER_PROCESSING']){
    await page.getByLabel('Разрешение',{exact:true}).selectOption(type);
    await page.getByLabel('Я прочитал(а) текст и явно подтверждаю это разрешение',{exact:true}).check();
    await page.getByRole('button',{name:'Сохранить согласие',exact:true}).click();
    await expect(page.getByLabel('Я прочитал(а) текст и явно подтверждаю это разрешение',{exact:true})).not.toBeChecked();
  }
  await page.getByRole('button',{name:'Аватары',exact:true}).click();
  await page.getByLabel('Название образа',{exact:true}).fill('Вымышленный тестовый образ');
  await page.getByLabel('Человек на фотографии',{exact:true}).selectOption({label:'Вымышленный представитель'});
  await page.getByLabel('Исходная фотография',{exact:true}).selectOption({label:'Тестовая фотография.png'});
  await page.getByRole('button',{name:'Создать образ · 5 кр.',exact:true}).click();
  const avatarCard=page.locator('article').filter({has:page.getByRole('heading',{name:'Вымышленный тестовый образ',exact:true})});
  await expect(avatarCard.getByText('Готово',{exact:true})).toBeVisible({timeout:60000});
  await expect(page.getByText('80 AI-кредитов',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Обновить каталог голосов',exact:true}).click();
  await avatarCard.getByLabel('Голос для Вымышленный тестовый образ',{exact:true}).selectOption({label:'Демо-голос · Russian'});
  await expect(page.getByRole('status')).toHaveText('Голос сохранён');
  await page.getByRole('button',{name:'Медиа',exact:true}).click();
  await page.getByRole('button',{name:'Аватары',exact:true}).click();
  await expect(avatarCard.getByLabel('Голос для Вымышленный тестовый образ',{exact:true})).not.toHaveValue('');
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  await page.screenshot({path:'test-results/avatars-mobile.png',fullPage:true});
  await page.setViewportSize({width:1440,height:1000});
  await page.screenshot({path:'test-results/avatars-desktop.png',fullPage:true});
  await page.getByRole('button',{name:'Видео',exact:true}).click();
  await page.getByLabel('Одобренный сценарий',{exact:true}).selectOption({label:'Мой проверенный заголовок · v2'});
  await page.getByLabel('Образ аватара',{exact:true}).selectOption({index:1});
  await page.getByLabel('Субтитры',{exact:true}).selectOption('AUTO');
  await page.getByRole('button',{name:'Создать видео',exact:true}).click();
  const videoCard=page.locator('article').filter({has:page.getByRole('heading',{name:'Мой проверенный заголовок',exact:true})});
  await expect(videoCard.getByRole('button',{name:'Редактировать субтитры',exact:true})).toBeVisible({timeout:90000});
  await videoCard.getByRole('button',{name:'Редактировать субтитры',exact:true}).click();
  await page.getByLabel('Субтитр 1',{exact:true}).fill('Проверенные субтитры');
  await page.getByLabel('Стиль субтитров',{exact:true}).selectOption('bold');
  await page.getByRole('button',{name:'Сохранить субтитры',exact:true}).click();
  await expect(page.getByText('Субтитры сохранены',{exact:true})).toBeVisible();
  await page.screenshot({path:'test-results/captions-desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  await page.screenshot({path:'test-results/captions-mobile.png',fullPage:true});
  await page.setViewportSize({width:1440,height:1000});
  await page.getByRole('button',{name:'Запустить финальный рендер',exact:true}).click();
  await expect(videoCard.getByText('Готово',{exact:true})).toBeVisible({timeout:60000});
  await videoCard.getByRole('button',{name:'Смотреть видео',exact:true}).click();
  const video=page.getByLabel('Готовый ролик',{exact:true});
  await expect(video).toBeVisible();
  await expect.poll(()=>video.evaluate(element=>(element as HTMLVideoElement).videoWidth)).toBe(720);
  await expect.poll(()=>video.evaluate(element=>(element as HTMLVideoElement).duration)).toBeGreaterThan(.8);
  await videoCard.getByRole('button',{name:'Одобрить видео',exact:true}).click();
  await expect(videoCard.getByText('Одобрено',{exact:true})).toBeVisible();
  await videoCard.getByRole('button',{name:'История обработки',exact:true}).click();
  await expect(videoCard.getByText('B-roll — отключено',{exact:true})).toBeVisible();
  await page.screenshot({path:'test-results/videos-desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  await page.screenshot({path:'test-results/videos-mobile.png',fullPage:true});
  await page.setViewportSize({width:1440,height:1000});
  await page.getByRole('button',{name:'Календарь',exact:true}).click();
  await page.getByLabel('Дата календаря',{exact:true}).fill('2026-10-06');
  await page.getByLabel('Часовой пояс календаря',{exact:true}).selectOption('Europe/Moscow');
  await page.getByRole('button',{name:'Добавить в план',exact:true}).click();
  await page.getByLabel('Название материала',{exact:true}).fill('Плановый тестовый ролик');
  await page.getByLabel('Тип материала',{exact:true}).selectOption('SHORT_VIDEO');
  await page.getByLabel('Одобренное видео',{exact:true}).selectOption({label:'Мой проверенный заголовок'});
  await page.getByLabel('Площадка плана',{exact:true}).selectOption('YOUTUBE');
  await page.getByLabel('Дата и время',{exact:true}).fill('2026-10-06T12:30');
  await page.getByLabel('Часовой пояс материала',{exact:true}).selectOption('Europe/Moscow');
  await page.getByLabel('Текст публикации',{exact:true}).fill('Проверенный текст публикации');
  await page.getByLabel('Хештеги',{exact:true}).fill('#контент #тест');
  await page.getByRole('button',{name:'Сохранить план',exact:true}).click();
  await expect(page.getByText('Материал сохранён в плане',{exact:true})).toBeVisible();
  const calendarItem=page.getByRole('button',{name:/Плановый тестовый ролик/});
  await expect(calendarItem).toContainText('12:30');
  await calendarItem.dragTo(page.getByRole('region',{name:'План 2026-10-07',exact:true}));
  await expect(page.getByText('Дата в плане изменена',{exact:true})).toBeVisible();
  await calendarItem.click();
  await expect(page.getByLabel('Дата и время',{exact:true})).toHaveValue('2026-10-07T12:30');
  await page.getByRole('button',{name:'Закрыть',exact:true}).click();
  await page.getByLabel('Вид календаря',{exact:true}).selectOption('week');
  await expect(calendarItem).toBeVisible();
  await page.getByLabel('Дата календаря',{exact:true}).fill('2026-10-07');
  await page.getByLabel('Вид календаря',{exact:true}).selectOption('day');
  await expect(calendarItem).toBeVisible();
  await page.screenshot({path:'test-results/calendar-desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  await page.screenshot({path:'test-results/calendar-mobile.png',fullPage:true});
  await calendarItem.click();
  await page.getByRole('button',{name:'Снять с плана',exact:true}).click();
  await expect(calendarItem).toHaveCount(0);
  await page.getByRole('button',{name:'Интеграции',exact:true}).click();
  await page.getByLabel('Канал Telegram',{exact:true}).fill('@contentos_demo');
  const botToken='123456:fixture_token_not_a_real_credential';
  await page.getByLabel('Токен Telegram-бота',{exact:true}).fill(botToken);
  const connectionResponse=page.waitForResponse(response=>response.url().endsWith('/social')&&response.request().method()==='POST');
  await page.getByRole('button',{name:'Проверить и подключить',exact:true}).click();
  expect(JSON.stringify(await (await connectionResponse).json())).not.toContain(botToken);
  await expect(page.getByLabel('Токен Telegram-бота',{exact:true})).toHaveValue('');
  const channelCard=page.locator('article').filter({has:page.getByRole('heading',{name:'Демонстрационный канал',exact:true})});
  await expect(channelCard.getByText('Готово',{exact:true})).toBeVisible();
  await channelCard.getByRole('button',{name:'Проверить права',exact:true}).click();
  await expect(page.getByText('Права подключения проверены',{exact:true})).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  await page.screenshot({path:'test-results/integrations-mobile.png',fullPage:true});
  await page.setViewportSize({width:1440,height:1000});
  await page.screenshot({path:'test-results/integrations-desktop.png',fullPage:true});
  await channelCard.getByRole('button',{name:'Отключить канал',exact:true}).click();
  await channelCard.getByRole('button',{name:'Подтвердить отключение',exact:true}).click();
  await expect(channelCard.getByText('Отключено',{exact:true})).toBeVisible();
  await channelCard.getByRole('button',{name:'Обновить токен',exact:true}).click();
  await page.getByLabel('Токен Telegram-бота',{exact:true}).fill(botToken);
  await page.getByRole('button',{name:'Проверить новый токен',exact:true}).click();
  await expect(channelCard.getByText('Готово',{exact:true})).toBeVisible();

  await page.getByRole('button',{name:'Календарь',exact:true}).click();
  const publishAt=new Date(Math.ceil((Date.now()+40000)/60000)*60000);
  await page.getByLabel('Дата календаря',{exact:true}).fill(publishAt.toISOString().slice(0,10));
  await page.getByRole('button',{name:'Добавить в план',exact:true}).click();
  await page.getByLabel('Название материала',{exact:true}).fill('Одобренный ролик для Telegram');
  await page.getByLabel('Тип материала',{exact:true}).selectOption('SHORT_VIDEO');
  await page.getByLabel('Одобренное видео',{exact:true}).selectOption({label:'Мой проверенный заголовок'});
  await page.getByLabel('Площадка плана',{exact:true}).selectOption('TELEGRAM');
  await page.getByLabel('Дата и время',{exact:true}).fill(publishAt.toISOString().slice(0,16));
  await page.getByLabel('Часовой пояс материала',{exact:true}).selectOption('UTC');
  await page.getByLabel('Текст публикации',{exact:true}).fill('Тест публикации одобренного ролика');
  await page.getByLabel('Разрешить комментарии',{exact:true}).uncheck();
  await page.getByRole('button',{name:'Сохранить план',exact:true}).click();
  await expect(page.getByText('Материал сохранён в плане',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Публикации',exact:true}).click();
  await page.getByLabel('Материал для публикации',{exact:true}).selectOption({label:'Одобренный ролик для Telegram'});
  await page.getByLabel('Канал публикации',{exact:true}).selectOption({label:'Демонстрационный канал (@contentos_demo)'});
  await page.getByRole('button',{name:'Просмотреть ролик перед публикацией',exact:true}).click();
  await expect(page.getByLabel('Видео перед публикацией',{exact:true})).toBeVisible();
  await page.getByLabel('Я проверил материал, канал и время отправки',{exact:true}).check();
  await page.getByRole('button',{name:'Одобрить и запланировать публикацию',exact:true}).click();
  await expect(page.getByText('Публикация одобрена и поставлена в очередь',{exact:true})).toBeVisible();
  const publicationCard=page.locator('article').filter({has:page.getByRole('heading',{name:'Одобренный ролик для Telegram',exact:true})});
  await expect(publicationCard.getByText('Опубликовано',{exact:true})).toBeVisible({timeout:120000});
  await page.screenshot({path:'test-results/publishing-desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  await page.screenshot({path:'test-results/publishing-mobile.png',fullPage:true});
  await page.setViewportSize({width:1440,height:1000});

  await page.getByRole('button',{name:'Аналитика',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Аналитика публикаций',exact:true})).toBeVisible();
  const channelAnalytics=page.getByRole('region',{name:'Показатели каналов',exact:true});
  await channelAnalytics.getByRole('button',{name:'Получить показатели канала',exact:true}).click();
  await expect(channelAnalytics.getByText('Данные получены',{exact:true})).toBeVisible({timeout:60000});
  await expect(channelAnalytics.getByText('ДЕМО: тестовые показатели',{exact:true})).toBeVisible();
  await channelAnalytics.getByRole('button',{name:'История показателей канала',exact:true}).click();
  await expect(channelAnalytics.getByRole('heading',{name:'Последние 100 наблюдений канала',exact:true})).toBeVisible();
  await expect(channelAnalytics.getByText(/1\s000 участников · ДЕМО/)).toBeVisible();

  const analyticsCard=page.locator('article').filter({has:page.getByRole('heading',{name:'Одобренный ролик для Telegram',exact:true})});
  await expect(analyticsCard.getByText('Наблюдений пока нет.',{exact:true})).toBeVisible();
  await page.getByLabel('Публикация для аналитики',{exact:true}).selectOption({label:'Одобренный ролик для Telegram · ДЕМО'});
  const observedAt=await page.evaluate(()=>{const date=new Date();date.setMilliseconds(0);return new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,19);});
  await page.getByLabel('Дата наблюдения',{exact:true}).fill(observedAt);
  await page.getByLabel('Источник показателей',{exact:true}).fill('Тестовое ручное наблюдение');
  await page.getByLabel('Просмотры',{exact:true}).fill('0');
  await page.getByRole('button',{name:'Сохранить показатели',exact:true}).click();
  await expect(page.getByRole('status')).toContainText('Показатели сохранены');
  await expect(analyticsCard.locator('dd').first()).toHaveText('0');
  await expect(analyticsCard.locator('dd').nth(1)).toHaveText('Нет данных');
  await page.reload();
  await page.getByRole('button',{name:'Аналитика',exact:true}).click();
  await expect(analyticsCard.locator('dd').first()).toHaveText('0');
  await analyticsCard.getByRole('button',{name:'История показателей',exact:true}).click();
  await expect(analyticsCard.locator('details')).toHaveCount(1);
  await page.screenshot({path:'test-results/analytics-desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  await page.screenshot({path:'test-results/analytics-mobile.png',fullPage:true});
  await page.setViewportSize({width:1440,height:1000});

  const studioUrl=new URL(page.url()),brainPath=`/api/organizations/${studioUrl.searchParams.get('organization')}/brands/${studioUrl.pathname.split('/')[2]}`;
  const beforeBrainResponse=await page.request.get(brainPath);expect(beforeBrainResponse.ok()).toBe(true);
  const beforeAnalysisBrain=await beforeBrainResponse.json();expect(beforeAnalysisBrain.data.brand.id).toBe(studioUrl.pathname.split('/')[2]);
  const performance=page.getByRole('region',{name:'AI-анализ эффективности',exact:true});
  await performance.getByRole('button',{name:'Проанализировать эффективность',exact:true}).click();
  await expect(performance.getByRole('heading',{name:'ДЕМО · Отчёт по эффективности',exact:true})).toBeVisible({timeout:90000});
  await expect(performance.getByText('Недостаточно данных',{exact:true})).toHaveCount(7);
  const firstReport=await performance.getByLabel('Сохранённый отчёт',{exact:true}).inputValue();
  const accept=performance.getByRole('button',{name:'Принять рекомендацию',exact:true});
  await expect(accept).toBeDisabled();
  await performance.getByLabel('Я проверил изменение и хочу создать новую версию стратегии',{exact:true}).check();
  await accept.click();
  await expect(performance.getByText('Принято · создана версия 2',{exact:true})).toBeVisible();
  await expect(performance.getByRole('heading',{name:'Текущая стратегия v2',exact:true})).toBeVisible();
  const afterBrainResponse=await page.request.get(brainPath);expect(afterBrainResponse.ok()).toBe(true);
  expect((await afterBrainResponse.json()).data).toEqual(beforeAnalysisBrain.data);
  await page.screenshot({path:'test-results/performance-desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  await page.screenshot({path:'test-results/performance-mobile.png',fullPage:true});
  await page.setViewportSize({width:1440,height:1000});
  await performance.getByRole('button',{name:'Проанализировать эффективность',exact:true}).click();
  await expect(performance.getByLabel('Сохранённый отчёт',{exact:true})).not.toHaveValue(firstReport,{timeout:90000});
  await performance.getByRole('button',{name:'Отклонить рекомендацию',exact:true}).click();
  await expect(performance.getByText('Отклонено · стратегия не изменена',{exact:true})).toBeVisible();
  await page.reload();
  await page.getByRole('button',{name:'Аналитика',exact:true}).click();
  await expect(performance.getByText('Отклонено · стратегия не изменена',{exact:true})).toBeVisible();
  await performance.getByLabel('Сохранённый отчёт',{exact:true}).selectOption(firstReport);
  await expect(performance.getByText('Принято · создана версия 2',{exact:true})).toBeVisible();

  await page.getByRole('button',{name:'Видео',exact:true}).click();
  await videoCard.getByRole('button',{name:'Удалить видео',exact:true}).click();
  await videoCard.getByRole('button',{name:'Подтвердить удаление видео',exact:true}).click();
  await expect(videoCard).toHaveCount(0,{timeout:30000});
  await page.getByRole('button',{name:'Аватары',exact:true}).click();
  await avatarCard.getByRole('button',{name:'Удалить аватар и все образы',exact:true}).click();
  await expect(avatarCard).toHaveCount(0,{timeout:30000});
  await page.getByRole('button',{name:'Медиа',exact:true}).click();
  await page.getByRole('button',{name:'Удалить фотографию',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Тестовая фотография.png',exact:true})).toHaveCount(0,{timeout:20000});
  await page.reload();
  await page.getByRole('button',{name:'Согласия',exact:true}).click();
  await expect(page.getByText('Отозвано',{exact:true})).toBeVisible();
  await page.getByRole('link',{name:'Все бренды',exact:true}).click();
  await page.setViewportSize({width:390,height:844});
  const sessionCookie = (await page.context().cookies()).find(cookie => cookie.name === 'contentos_session');
  expect(sessionCookie?.httpOnly).toBe(true);
  expect(sessionCookie?.sameSite).toBe('Lax');
  await page.getByRole('button', { name: 'Выйти из аккаунта', exact: true }).click();
  await expect(page).toHaveURL(/\/login$/);
  expect((await page.request.get('/api/organizations')).status()).toBe(401);
  expect(errors).toEqual([]);
});
test('rejects CSRF and anonymous access without exposing sensitive data', async ({ request }) => {
  const csrf = await request.post('/api/auth/login', { headers: { origin: 'https://untrusted.example' }, data: { email: 'test@example.test', password: 'test-password' } });
  expect(csrf.status()).toBe(403);
  const anonymous = await request.get('/api/organizations');
  expect(anonymous.status()).toBe(401);
  expect(JSON.stringify(await anonymous.json())).not.toContain('passwordHash');
});
