import { test, expect } from '@playwright/test';
import { randomUUID, randomBytes, createHash } from 'node:crypto';
import { BrandRepository, createDatabase } from '../../packages/db/src/index';
import { BrandService } from '../../packages/core/src/brands';
import { hashPassword } from '../../packages/core/src/password';
import { emptyOnboarding } from '../../packages/types/src/index';
const url = process.env.TEST_DATABASE_URL;
if (!url || !new URL(url).pathname.endsWith('_test')) throw new Error('Dedicated test database required');
const database = createDatabase(url);
test.afterAll(() => database.close());
test('privacy center registers and cancels a request and revokes every session', async ({ page, context, browser, baseURL }, testInfo) => {
  const user = randomUUID(), password = 'Fixture privacy password 123!', correlation = randomUUID();
  await database.client`insert into users(id,email,name,password_hash,email_verified_at) values(${user},${`${user}@example.test`},'Privacy browser fixture',${await hashPassword(password)},now())`;
  async function session() {
    const token = randomBytes(32).toString('base64url');
    await database.client`insert into sessions(user_id,token_hash,expires_at) values(${user},${createHash('sha256').update(token).digest('hex')},now()+interval '1 hour')`;
    return token;
  }
  const brands = new BrandService(new BrandRepository(database.db));
  const tenant = (await brands.createOrganization(user, { name: 'Privacy brand owner' }, correlation)).id;
  const workspace = (await brands.overview(user, tenant)).workspaces[0]!;
  const brand = await brands.createBrand(user, tenant, { name: 'Privacy brand', workspaceId: workspace.id }, correlation);
  await brands.saveOnboarding(user, tenant, brand.id, { data: { ...emptyOnboarding('Privacy brand'), niche: 'Testing', geography: 'Online', usp: 'Clear', voice: 'Calm', products: [{ name: 'Product', description: '' }], audience: [{ name: 'Audience', description: '' }], pains: [{ name: 'Pain', description: '' }], goals: ['Trust'], platforms: ['TELEGRAM'], ctas: [{ name: 'Read', description: '' }] }, revision: 0, step: 14, complete: true }, correlation);
  await context.addCookies([{ name: 'contentos_session', value: await session(), url: baseURL!, httpOnly: true, sameSite: 'Lax' }]);
  const second = await browser.newContext({ baseURL });
  await second.addCookies([{ name: 'contentos_session', value: await session(), url: baseURL!, httpOnly: true, sameSite: 'Lax' }]);
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  try {
    await page.goto('/dashboard'); await page.getByRole('link', { name: 'Приватность', exact: true }).click();
    await expect(page.getByRole('heading', { name: 'Приватность', exact: true })).toBeVisible();
    await expect(page.getByRole('link', { name: 'Отозвать согласия', exact: true })).toHaveAttribute('href', `/brands/${brand.id}/content?organization=${tenant}&tab=consents`);
    await page.getByRole('link', { name: 'Отозвать согласия', exact: true }).click();
    await expect(page.getByRole('heading', { name: 'История разрешений', exact: true })).toBeVisible();
    await page.goto('/privacy');
    await expect(page.getByText('Активных сессий: 2', { exact: true })).toBeVisible();
    expect((await page.request.post('/api/privacy/deletion', { data: { password, acknowledged: true, idempotencyKey: randomUUID() } })).status()).toBe(403);
    await page.getByLabel('Текущий пароль', { exact: true }).fill('wrong-password');
    await page.getByRole('checkbox', { name: 'Я понимаю, что отправляю запрос, а удаление ещё не выполнено.' }).check();
    page.once('dialog', dialog => dialog.accept()); await page.getByRole('button', { name: 'Запросить удаление аккаунта', exact: true }).click();
    await expect(page.getByRole('alert').filter({ hasText: 'Нет доступа' })).toContainText('Нет доступа');
    await expect(page.getByLabel('Текущий пароль', { exact: true })).toHaveValue('');
    await page.getByLabel('Текущий пароль', { exact: true }).fill(password);
    page.once('dialog', dialog => dialog.accept()); await page.getByRole('button', { name: 'Запросить удаление аккаунта', exact: true }).click();
    await expect(page.getByRole('status')).toContainText('Запрос зарегистрирован');
    await page.reload();
    await expect(page.getByRole('button', { name: 'Отменить запрос', exact: true })).toBeVisible();
    expect(await database.client`select id from account_deletion_requests where user_id=${user} and status='REQUESTED'`).toHaveLength(1);
    const response = await page.request.get('/api/privacy'); expect(response.headers()['cache-control']).toBe('no-store'); expect(await response.text()).not.toContain(password);
    await page.screenshot({ path: testInfo.outputPath('privacy-desktop.png'), fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await page.screenshot({ path: testInfo.outputPath('privacy-mobile.png'), fullPage: true });
    await page.getByRole('button', { name: 'Отменить запрос', exact: true }).click(); await expect(page.getByRole('status')).toContainText('Запрос отменён.');
    await expect(page.getByRole('button', { name: 'Запросить удаление аккаунта', exact: true })).toBeVisible();
    expect((await second.request.get('/api/me')).status()).toBe(200);
    page.once('dialog', dialog => dialog.accept()); await page.getByRole('button', { name: 'Выйти на всех устройствах', exact: true }).click();
    await expect(page).toHaveURL(/\/login$/); expect((await second.request.get('/api/me')).status()).toBe(401);
    expect(errors).toEqual([]);
  } finally { await second.close(); await database.client`delete from sessions where user_id=${user}`; }
});
