import { drizzle } from 'drizzle-orm/postgres-js';
import postgres from 'postgres';
import * as schema from './schema';
export * from './schema';
export function createDatabase(url: string) {
  const client = postgres(url, { max: 5, prepare: false, idle_timeout: 20, connect_timeout: 10 });
  return { client, db: drizzle(client, { schema }), close: () => client.end() };
}
export type Database = ReturnType<typeof createDatabase>['db'];
export * from './repositories/auth';
export * from './repositories/brands';
export * from './repositories/ledger';
export * from './repositories/jobs';
export * from './repositories/ai-calls';
export * from './repositories/content';
export * from './repositories/consent';
export * from './repositories/media';
export * from './repositories/avatars';
export * from './repositories/voices';
export * from './repositories/videos';
export * from './repositories/calendar';
export * from './repositories/social';
export * from './repositories/publishing';
export * from './repositories/analytics';
export * from './repositories/channel-analytics';
export * from './repositories/performance';
export * from './repositories/billing';
export * from './repositories/renewal';
export * from './repositories/payment-tasks';
export * from './repositories/payment-webhooks';
export * from './repositories/renewal-billing';
