'use client';
import {useCallback,useEffect,useState,type FormEvent} from 'react';
import type {ConsentService} from '@contentos/core';
import type {ConsentType} from '@contentos/types';
import {api} from '../lib/api-client';
type Overview=Awaited<ReturnType<ConsentService['overview']>>;
const names:Record<ConsentType,string>={OWN_LIKENESS:'Моё изображение',THIRD_PARTY_LIKENESS:'Изображение другого человека',VOICE_CLONING:'Клонирование голоса',CROSS_BORDER_PROCESSING:'Обработка во внешнем AI-сервисе',AUTOMATED_PUBLISHING:'Автоматическая публикация'};
export function ConsentCenter({base,role}:{base:string;role:string}){
  const [data,setData]=useState<Overview|null>(null),[subjectId,setSubjectId]=useState(''),[type,setType]=useState<ConsentType>('OWN_LIKENESS'),[checked,setChecked]=useState(false),[pending,setPending]=useState(false),[error,setError]=useState('');
  const load=useCallback(async()=>{const result=await api<Overview>(`${base}/consents`);setData(result);setSubjectId(current=>current||result.subjects[0]?.id||'');},[base]);
  useEffect(()=>{void load().catch(failure=>setError(failure instanceof Error?failure.message:'Ошибка загрузки'));},[load]);
  const policy=data?.policies.find(item=>item.type===type);const canManage=['OWNER','ADMIN','MANAGER'].includes(role);
  async function perform(action:()=>Promise<unknown>){setPending(true);setError('');try{await action();await load();setChecked(false);}catch(failure){setError(failure instanceof Error?failure.message:'Не удалось сохранить');}finally{setPending(false);}}
  function addSubject(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);void perform(async()=>{const created=await api<{id:string}>(`${base}/consents/subjects`,'POST',{name:form.get('name'),type:form.get('type')});setSubjectId(created.id);});}
  return <section><h2>Согласия и права</h2><p className="muted">Разрешения привязаны к конкретному человеку, голосу или организации и этому бренду. Отзыв запрещает следующие операции, требующие этого разрешения.</p>{error?<p className="notice error" role="alert">{error}</p>:null}
    {canManage?<form className="panel inline-form" onSubmit={addSubject}><label>Имя субъекта<input name="name" required maxLength={200}/></label><label>Тип субъекта<select name="type"><option value="PERSON">Человек</option><option value="VOICE">Голос</option><option value="ORGANIZATION">Организация</option></select></label><button className="button secondary" disabled={pending}>Добавить субъекта</button></form>:null}
    {data?.subjects.length?<div className="panel stack"><label>Субъект<select value={subjectId} onChange={e=>{setSubjectId(e.target.value);setChecked(false);}}>{data.subjects.map(subject=><option key={subject.id} value={subject.id}>{subject.name}</option>)}</select></label><label>Разрешение<select value={type} onChange={e=>{setType(e.target.value as ConsentType);setChecked(false);}}>{Object.entries(names).map(([key,name])=><option value={key} key={key}>{name}</option>)}</select></label><p className="preserve-lines">{policy?.text}</p><small className="muted">Версия: {policy?.version}</small><label className="consent-checkbox"><input type="checkbox" checked={checked} disabled={!canManage} onChange={e=>setChecked(e.target.checked)}/>Я прочитал(а) текст и явно подтверждаю это разрешение</label><button className="button primary" disabled={!checked||!policy||pending||!canManage} onClick={()=>void perform(()=>api(`${base}/consents`,'POST',{subjectId,type,version:policy!.version,textHash:policy!.textHash,accepted:true,idempotencyKey:crypto.randomUUID()}))}>Сохранить согласие</button></div>:<div className="panel empty">Добавьте субъекта, чтобы сохранить разрешение.</div>}
    <h3>История разрешений</h3>{data?.records.map(record=><article className="panel" key={record.id}><strong>{names[record.type]}</strong><p>{data.subjects.find(subject=>subject.id===record.subjectId)?.name} · {record.version}</p><span className="badge">{record.revokedAt?'Отозвано':'Действует'}</span>{!record.revokedAt?<button className="button secondary" disabled={pending} onClick={()=>void perform(()=>api(`${base}/consents/${record.id}/revoke`,'POST'))}>Отозвать согласие</button>:null}</article>)}</section>;
}
