'use client';
import {useEffect,useRef,useState} from 'react';
import type {CalendarService,VideoService} from '@contentos/core';
import {calendarFieldsSchema,calendarInstant,localMinute,type CalendarFields} from '@contentos/types';
import {api} from '../lib/api-client';
type Entry=Awaited<ReturnType<CalendarService['list']>>[number];
type Video=Awaited<ReturnType<VideoService['overview']>>['projects'][number];
const names={SHORT_VIDEO:'Видео',POST:'Пост',CAROUSEL:'Карусель',STORY:'История',IMAGE:'Изображение'};
const addDays=(date:string,amount:number)=>new Date(Date.parse(`${date}T12:00:00Z`)+amount*86400000).toISOString().slice(0,10);
function daysFor(anchor:string,view:'day'|'week'|'month'){
  if(view==='day')return [anchor];
  const start=view==='month'?`${anchor.slice(0,7)}-01`:anchor;
  const weekday=new Date(`${start}T12:00:00Z`).getUTCDay();
  const monday=addDays(start,-((weekday+6)%7));return Array.from({length:view==='month'?42:7},(_,index)=>addDays(monday,index));
}
const fields=(entry:Entry):CalendarFields=>({title:entry.title,type:entry.type,videoProjectId:entry.videoProjectId,platform:entry.platform as CalendarFields['platform'],localDateTime:localMinute(new Date(entry.plannedAt),entry.timeZone),timeZone:entry.timeZone,disambiguation:calendarInstant(localMinute(new Date(entry.plannedAt),entry.timeZone),entry.timeZone,'EARLIER').getTime()===new Date(entry.plannedAt).getTime()?'EARLIER':'LATER',caption:entry.caption,hashtags:entry.hashtags,privacy:entry.privacy,commentsEnabled:entry.commentsEnabled,publishingMode:entry.publishingMode});
export function ContentCalendar({base,canWrite}:{base:string;canWrite:boolean}){
  const [zone,setZone]=useState(()=>Intl.DateTimeFormat().resolvedOptions().timeZone),[anchor,setAnchor]=useState(()=>localMinute(new Date(),Intl.DateTimeFormat().resolvedOptions().timeZone).slice(0,10)),[view,setView]=useState<'day'|'week'|'month'>('month');
  const [entries,setEntries]=useState<Entry[]>([]),[videos,setVideos]=useState<Video[]>([]),[loading,setLoading]=useState(true),[pending,setPending]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[refresh,setRefresh]=useState(0);
  const [draft,setDraft]=useState<CalendarFields|null>(null),[selected,setSelected]=useState<Entry|null>(null),[tags,setTags]=useState('');
  const intent=useRef<{payload:string;key:string}|null>(null);
  const requestVersion=useRef(0);
  const days=daysFor(anchor,view),first=days[0]!,last=days.at(-1)!;
  const from=new Date(Date.parse(`${first}T00:00:00Z`)-36*3600000).toISOString(),to=new Date(Date.parse(`${last}T00:00:00Z`)+60*3600000).toISOString();
  useEffect(()=>{let active=true;const version=++requestVersion.current;Promise.all([api<Entry[]>(`${base}/calendar?from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}`),api<Awaited<ReturnType<VideoService['overview']>>>(`${base}/videos`)]).then(([rows,overview])=>{if(active&&version===requestVersion.current){setEntries(rows);setVideos(overview.projects);setLoading(false);}}).catch(failure=>{if(active&&version===requestVersion.current){setError(failure instanceof Error?failure.message:'Не удалось загрузить календарь');setLoading(false);}});return()=>{active=false;};},[base,from,to,refresh]);
  const grouped=new Map<string,Entry[]>();
  for(const entry of entries){const day=localMinute(new Date(entry.plannedAt),zone).slice(0,10);const group=grouped.get(day)??[];group.push(entry);grouped.set(day,group);}
  function navigate(direction:number){if(view==='month'){const date=new Date(`${anchor.slice(0,7)}-01T12:00Z`);date.setUTCMonth(date.getUTCMonth()+direction);setAnchor(date.toISOString().slice(0,10));}else setAnchor(addDays(anchor,direction*(view==='week'?7:1)));}
  const ready=videos.filter(video=>video.stage==='READY'&&video.lifecycle==='ACTIVE'&&video.approvedAt);
  async function perform(action:()=>Promise<void>){const version=++requestVersion.current;setPending(true);setError('');setNotice('');try{await action();if(version!==requestVersion.current){setRefresh(value=>value+1);return;}const [rows,overview]=await Promise.all([api<Entry[]>(`${base}/calendar?from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}`),api<Awaited<ReturnType<VideoService['overview']>>>(`${base}/videos`)]);if(version===requestVersion.current){setEntries(rows);setVideos(overview.projects);setLoading(false);}}catch(failure){setError(failure instanceof Error?failure.message:'Не удалось сохранить план');}finally{setPending(false);}}
  function edit(entry:Entry){setSelected(entry);setDraft(fields(entry));setTags(entry.hashtags.join(' '));intent.current=null;}
  function create(){setSelected(null);setDraft(calendarFieldsSchema.parse({type:'POST',platform:'TELEGRAM',localDateTime:`${anchor}T12:00`,timeZone:zone,title:'Новый материал'}));setTags('');intent.current=null;}
  function patch(value:Partial<CalendarFields>){setDraft(current=>current?{...current,...value}:null);}
  async function move(id:string,date:string){const entry=entries.find(item=>item.id===id);if(!entry||!canWrite||pending)return;await perform(async()=>{const time=localMinute(new Date(entry.plannedAt),zone).slice(11);await api(`${base}/calendar/${entry.id}`,'PUT',{...fields(entry),timeZone:zone,localDateTime:`${date}T${time}`,disambiguation:undefined,revision:entry.revision});setNotice('Дата в плане изменена');});}
  return <section className="stack"><div className="section-heading"><h2>Календарь контента</h2>{canWrite?<button className="button primary" disabled={pending} onClick={create}>Добавить в план</button>:null}</div>
    <p className="notice warning">Сохранение даты создаёт план. Для отправки в Telegram одобрите материал во вкладке «Публикации». Перед изменением одобренного плана отмените ожидающую отправку.</p>
    {error?<p className="notice error" role="alert">{error}</p>:null}{notice?<p className="notice success" role="status">{notice}</p>:null}
    <div className="studio-form"><label>Дата календаря<input aria-label="Дата календаря" type="date" value={anchor} onChange={event=>{if(event.target.value)setAnchor(event.target.value);}}/></label><label>Вид календаря<select aria-label="Вид календаря" value={view} onChange={event=>setView(event.target.value as typeof view)}><option value="day">День</option><option value="week">Неделя</option><option value="month">Месяц</option></select></label><label>Часовой пояс календаря<select aria-label="Часовой пояс календаря" value={zone} onChange={event=>setZone(event.target.value)}>{Array.from(new Set([zone,'UTC',...Intl.supportedValuesOf('timeZone')])).map(value=><option key={value}>{value}</option>)}</select></label></div>
    <div className="studio-actions"><button className="button secondary" onClick={()=>navigate(-1)}>Назад</button><button className="button secondary" onClick={()=>setAnchor(localMinute(new Date(),zone).slice(0,10))}>Сегодня</button><button className="button secondary" onClick={()=>navigate(1)}>Вперёд</button><button className="text-button" onClick={()=>setRefresh(value=>value+1)}>Обновить календарь</button></div>
    {draft?<form className="panel stack" aria-label="Материал в календаре" onSubmit={event=>{event.preventDefault();void perform(async()=>{const input=calendarFieldsSchema.parse({...draft,hashtags:tags.split(/[\s,]+/).map(tag=>tag.replace(/^#/,'' )).filter(Boolean)});if(selected)await api(`${base}/calendar/${selected.id}`,'PUT',{...input,revision:selected.revision});else{const payload=JSON.stringify(input);if(intent.current?.payload!==payload)intent.current={payload,key:crypto.randomUUID()};await api(`${base}/calendar`,'POST',{...input,idempotencyKey:intent.current.key});}setDraft(null);setSelected(null);intent.current=null;setNotice('Материал сохранён в плане');});}}>
      <h3>{selected?'Материал в плане':'Новый материал'}</h3><fieldset className="stack" disabled={!canWrite||pending}><label>Название материала<input aria-label="Название материала" required maxLength={200} value={draft.title} onChange={event=>patch({title:event.target.value})}/></label>
      <div className="studio-form"><label>Тип материала<select aria-label="Тип материала" value={draft.type} onChange={event=>patch({type:event.target.value as CalendarFields['type'],videoProjectId:null})}>{Object.entries(names).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label>Площадка плана<select aria-label="Площадка плана" value={draft.platform} onChange={event=>patch({platform:event.target.value as CalendarFields['platform']})}>{['TELEGRAM','YOUTUBE','TIKTOK','INSTAGRAM','VK'].map(value=><option key={value}>{value}</option>)}</select></label></div>
      {['SHORT_VIDEO','STORY'].includes(draft.type)?<label>Одобренное видео<select aria-label="Одобренное видео" value={draft.videoProjectId??''} onChange={event=>patch({videoProjectId:event.target.value||null})}><option value="">Пока без видео</option>{ready.map(video=><option key={video.id} value={video.id}>{video.title}</option>)}</select></label>:null}
      <div className="studio-form"><label>Дата и время<input aria-label="Дата и время" type="datetime-local" required value={draft.localDateTime} onChange={event=>patch({localDateTime:event.target.value})}/></label><label>Часовой пояс материала<select aria-label="Часовой пояс материала" value={draft.timeZone} onChange={event=>patch({timeZone:event.target.value})}>{Array.from(new Set([draft.timeZone,'UTC',...Intl.supportedValuesOf('timeZone')])).map(value=><option key={value}>{value}</option>)}</select></label><label>Повторяющееся время<select aria-label="Повторяющееся время" value={draft.disambiguation??''} onChange={event=>patch({disambiguation:event.target.value?event.target.value as 'EARLIER'|'LATER':undefined})}><option value="">Не выбрано</option><option value="EARLIER">Первое вхождение</option><option value="LATER">Второе вхождение</option></select></label></div>
      <p className="muted">При переводе часов назад укажите первое или второе вхождение повторяющегося времени. Время, пропущенное при переводе часов вперёд, сохранить нельзя.</p>
      <label>Текст публикации<textarea aria-label="Текст публикации" rows={4} maxLength={20000} value={draft.caption} onChange={event=>patch({caption:event.target.value})}/></label><label>Хештеги<input aria-label="Хештеги" maxLength={3030} value={tags} onChange={event=>setTags(event.target.value)}/></label>
      <div className="studio-form"><label>Доступность<select value={draft.privacy} onChange={event=>patch({privacy:event.target.value as CalendarFields['privacy']})}><option value="PUBLIC">Публично</option><option value="UNLISTED">По ссылке</option><option value="PRIVATE">Приватно</option></select></label><label>Режим публикации<select value={draft.publishingMode} onChange={event=>patch({publishingMode:event.target.value as CalendarFields['publishingMode']})}><option value="APPROVAL">С одобрением</option><option value="MANUAL">Вручную</option></select></label></div><label><input type="checkbox" checked={draft.commentsEnabled} onChange={event=>patch({commentsEnabled:event.target.checked})}/>Разрешить комментарии</label></fieldset>
      <div className="studio-actions"><button className="button primary" disabled={pending||!canWrite}>Сохранить план</button><button type="button" className="button secondary" disabled={pending} onClick={()=>setDraft(null)}>Закрыть</button>{selected?<button type="button" className="text-button" disabled={pending||!canWrite} onClick={()=>void perform(async()=>{await api(`${base}/calendar/${selected.id}/cancel`,'POST',{revision:selected.revision});setDraft(null);setNotice('Материал снят с плана');})}>Снять с плана</button>:null}</div>
    </form>:null}
    {loading?<p role="status">Загружаем календарь…</p>:null}
    <div className={`calendar-grid calendar-view-${view}`}>{days.map(day=><section className="calendar-day" key={day} aria-label={`План ${day}`} onDragOver={event=>{if(canWrite)event.preventDefault();}} onDrop={event=>{event.preventDefault();void move(event.dataTransfer.getData('text/plain'),day);}}><h3>{new Intl.DateTimeFormat('ru',{day:'numeric',month:'short',weekday:'short',timeZone:'UTC'}).format(new Date(`${day}T12:00Z`))}</h3>{(grouped.get(day)??[]).map(entry=><button key={entry.id} className="calendar-item" disabled={pending} draggable={canWrite&&!pending} onDragStart={event=>event.dataTransfer.setData('text/plain',entry.id)} onClick={()=>edit(entry)}><time>{localMinute(new Date(entry.plannedAt),zone).slice(11)}</time><strong>{entry.title}</strong><small>{names[entry.type]} · {entry.platform}</small><small>{entry.videoProjectId?(entry.videoLifecycle==='ACTIVE'&&entry.videoStage==='READY'&&entry.videoApprovedAt?'Видео прикреплено':'Видео недоступно для публикации'):'Материал в подготовке'}</small></button>)}</section>)}</div>
  </section>;
}
