'use client';
import {useEffect,useRef,useState} from 'react';
import type {GenerationService,PerformanceService} from '@contentos/core';
import {metricLabels,type StrategyPatch} from '@contentos/types';
import {api} from '../lib/api-client';
type Reports=Awaited<ReturnType<PerformanceService['list']>>;
type Overview=Awaited<ReturnType<GenerationService['overview']>>;
const dimensions={TOPICS:'Темы',HOOKS:'Хуки',FORMATS:'Форматы',DURATION:'Продолжительность',CTAS:'Призывы к действию',AUDIENCE:'Аудитория',OUTLIERS:'Выделяющиеся публикации'};
const fields:Record<StrategyPatch['field'],string>={frequency:'Частота публикаций',toneOfVoice:'Тон коммуникации',formats:'Форматы',ctas:'Призывы к действию',hypotheses:'Гипотезы'};
function valueText(value:string|string[]|undefined){return Array.isArray(value)?value.join('\n'):value??'Нет данных';}
export function PerformanceStudio({base,canManage,overview}:{base:string;canManage:boolean;overview:Overview}){
  const [reports,setReports]=useState<Reports|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[pending,setPending]=useState(false),[refresh,setRefresh]=useState(0),[days,setDays]=useState(30),[selected,setSelected]=useState(''),[confirmed,setConfirmed]=useState(''),[submittedJob,setSubmittedJob]=useState('');
  const intent=useRef<{payload:string;key:string}|null>(null),sequence=useRef(0);
  const jobs=overview.jobs.filter(job=>job.type==='OPTIMIZE_STRATEGY'),finished=jobs.filter(job=>job.status==='SUCCEEDED').map(job=>job.id).join(','),running=jobs.some(job=>['QUEUED','RUNNING','RETRY'].includes(job.status))||!!submittedJob&&!jobs.some(job=>job.id===submittedJob);
  const cost=overview.usage.policies.find(policy=>policy.operation==='OPTIMIZE_STRATEGY')?.amount;
  const latest=overview.strategies[0],ready=!!overview.configuration.analyticsAI&&overview.configuration.ready&&cost!==undefined;
  useEffect(()=>{const request=++sequence.current;api<Reports>(`${base}/performance`).then(rows=>{if(request===sequence.current)setReports(rows);}).catch(failure=>{if(request===sequence.current)setError(failure instanceof Error?failure.message:'Не удалось загрузить отчёты');});return()=>{sequence.current++;};},[base,finished,refresh]);
  const report=reports?.find(row=>row.id===selected)??reports?.[0];
  async function submit(path:string,body:Record<string,unknown>,message:string){
    setPending(true);setConfirmed('');setError('');setNotice('');
    const payload=JSON.stringify({path,body});if(intent.current?.payload!==payload)intent.current={payload,key:crypto.randomUUID()};
    try{const result=await api<{id:string}>(`${base}/${path}`,'POST',{...body,idempotencyKey:intent.current.key});if(path==='jobs')setSubmittedJob(result.id);intent.current=null;setNotice(message);const request=++sequence.current;const rows=await api<Reports>(`${base}/performance`);if(request===sequence.current)setReports(rows);}
    catch(failure){setError(failure instanceof Error?failure.message:'Не удалось выполнить действие');}finally{setPending(false);}
  }
  return <section className="panel stack" aria-labelledby="performance-heading"><div className="section-heading"><div><p className="eyebrow">Performance Analyst</p><h2 id="performance-heading">AI-анализ эффективности</h2></div><span className="badge">Изменения после проверки</span></div>
    <p className="muted">Анализ сохранённых показателей публикаций. Выводы описывают наблюдения и гипотезы, а не доказанную причинность. Общие показатели канала не приписываются отдельным постам.</p>
    {!ready?<p className="notice warning">AI-анализ отключён или требует настройки провайдера и тарифной политики.</p>:null}
    {error?<p role="alert" className="notice error">{error}</p>:null}{notice?<p role="status" className="notice success">{notice}</p>:null}
    <label>Период AI-анализа<select value={days} disabled={pending||running} onChange={event=>setDays(Number(event.target.value))}><option value={7}>7 дней</option><option value={30}>30 дней</option><option value={90}>90 дней</option></select></label>
    <p className="muted">Нужны сохранённая стратегия и хотя бы одно наблюдение. Анализируются последние 50 публикаций за период. Стоимость: {cost===undefined?'не настроена':`${cost} AI-кредитов`}. При окончательной ошибке резерв возвращается.</p>
    <button className="button primary" disabled={!canManage||!ready||!latest||pending||running} onClick={()=>void submit('jobs',{type:'OPTIMIZE_STRATEGY',options:{analysisDays:days}},'Анализ поставлен в очередь.')}>{running?'Анализ выполняется…':'Проанализировать эффективность'}</button>
    <button className="text-button" disabled={pending} onClick={()=>{setError('');setRefresh(value=>value+1);}}>Обновить отчёты</button>
    {jobs[0]?.status==='FAILED'?<p className="notice error">Анализ не завершён: {jobs[0].errorCode}. Кредиты возвращены.</p>:null}
    {!reports?<p>Загружаем отчёты…</p>:!reports.length?<p className="muted">Отчётов пока нет. После завершения анализа здесь появятся выводы и рекомендации.</p>:null}
    {report?<><label>Сохранённый отчёт<select value={report.id} disabled={pending} onChange={event=>{setSelected(event.target.value);setConfirmed('');}}>{reports?.map(row=><option key={row.id} value={row.id}>{new Date(row.createdAt).toLocaleString('ru')} · стратегия v{row.strategyVersion}</option>)}</select></label>
      <h3>{report.provider==='mock'?'ДЕМО · ':''}Отчёт по эффективности</h3><p>{report.output.summary}</p><p className="muted">Период публикаций: {new Date(report.evidence.windowStart).toLocaleDateString('ru')} — {new Date(report.evidence.windowEnd).toLocaleDateString('ru')}. Использовано {report.evidence.publications.length} из {report.evidence.totalPublications}; с измерениями: {report.evidence.publications.filter(row=>row.observation).length}. Снимок данных: {new Date(report.evidence.generatedAt).toLocaleString('ru')}.{report.evidence.truncated?' Выборка ограничена последними 50 публикациями.':''}</p>
      <ul>{report.output.limitations.map((text,index)=><li key={index}>{text}</li>)}</ul>
      <div className="analytics-inputs">{report.output.findings.map(finding=><article className="panel stack" key={finding.dimension}><h4>{dimensions[finding.dimension]}</h4><span className="badge">{finding.status==='INSUFFICIENT_DATA'?'Недостаточно данных':'Наблюдаемое сравнение'}</span><p>{finding.explanation}</p>{finding.metric?<p>{metricLabels[finding.metric]}</p>:null}<div>{finding.evidenceIds.map(id=><a key={id} className="text-button" href={`#observation-${report.id}-${id}`}>Наблюдение {id.slice(0,8)} </a>)}</div></article>)}</div>
      <details><summary>Источники и использованные показатели</summary>{report.evidence.publications.map(row=><article className="panel" key={row.publicationId} id={row.observation?`observation-${report.id}-${row.observation.id}`:undefined}><h4>{row.title}</h4><p>{row.provider} · {row.format} · опубликовано {new Date(row.publishedAt).toLocaleString('ru')}</p>{row.observation?<><p>{row.observation.source} · {row.observation.sourceNote} · наблюдение {new Date(row.observation.observedAt).toLocaleString('ru')}</p><dl className="analytics-metrics">{Object.entries(row.observation.metrics).filter(([,value])=>value!==null).map(([key,value])=><div key={key}><dt>{metricLabels[key as keyof typeof metricLabels]}</dt><dd>{value}</dd></div>)}</dl></>:<p>Измерений нет.</p>}</article>)}</details>
      <h3>Что протестировать дальше</h3><p className="muted">Принятие создаёт новую версию стратегии. Brand Brain не изменяется. Если стратегия или профиль бренда изменились после анализа, сформируйте новый отчёт.</p>
      {report.recommendations.map(recommendation=><article key={recommendation.id} className="panel stack"><h4>{recommendation.content.title}</h4><p>{recommendation.content.rationale}</p><p><strong>Гипотеза:</strong> {recommendation.content.hypothesis}</p><p>{metricLabels[recommendation.content.successMetric]} · {recommendation.content.horizonDays} дней. {recommendation.content.successRule}</p>
        <p>{recommendation.content.evidenceIds.length?recommendation.content.evidenceIds.map(id=><a key={id} className="text-button" href={`#observation-${report.id}-${id}`}>Наблюдение {id.slice(0,8)} </a>):'Гипотеза для измерения: подтверждающих наблюдений нет.'}</p><p><strong>Изменение:</strong> {fields[recommendation.content.patch.field]}</p><div className="analytics-inputs"><div><h5>Текущая стратегия v{latest?.version}</h5><p style={{whiteSpace:'pre-wrap'}}>{valueText(latest?.content[recommendation.content.patch.field])}</p></div><div><h5>Предложенное значение</h5><p style={{whiteSpace:'pre-wrap'}}>{valueText(recommendation.content.patch.value)}</p></div></div>
        {recommendation.decision?<p className="notice success">{recommendation.decision==='ACCEPTED'?`Принято · создана версия ${recommendation.appliedVersion}`:'Отклонено · стратегия не изменена'}</p>:<><label className="checkbox-label"><input type="checkbox" checked={confirmed===recommendation.id} disabled={!canManage||!ready||pending} onChange={event=>setConfirmed(event.target.checked?recommendation.id:'')}/>Я проверил изменение и хочу создать новую версию стратегии</label><div className="button-row"><button className="button primary" disabled={!canManage||!ready||pending||confirmed!==recommendation.id||!latest} onClick={()=>void submit('performance',{recommendationId:recommendation.id,decision:'ACCEPTED',expectedVersion:latest!.version},'Рекомендация принята. Создана новая версия стратегии.')}>Принять рекомендацию</button><button className="button secondary" disabled={!canManage||!ready||pending||!latest} onClick={()=>void submit('performance',{recommendationId:recommendation.id,decision:'REJECTED',expectedVersion:latest!.version},'Рекомендация отклонена.')}>Отклонить рекомендацию</button></div></>}
      </article>)}
    </>:null}
  </section>;
}
