'use client';
import { useCallback, useEffect, useRef, useState, type FormEvent } from 'react';
import Link from 'next/link';
import type { Role } from '@contentos/types';
import { api } from '../lib/api-client';
const labels:Record<Role,string>={OWNER:'Владелец',ADMIN:'Администратор',MANAGER:'Менеджер',EDITOR:'Редактор',CLIENT_APPROVER:'Согласующий',VIEWER:'Наблюдатель'};
const assignable:Exclude<Role,'OWNER'>[]=['ADMIN','MANAGER','EDITOR','CLIENT_APPROVER','VIEWER'];
type Member={userId:string;name:string;email:string;role:Role;revision:string;verifiedAt:string|null;disabledAt:string|null};
type Invitation={id:string;email:string;role:Exclude<Role,'OWNER'>;expiresAt:string;acceptedAt:string|null;revokedAt:string|null};
type Overview={userId:string;role:Role;members:Member[];invitations:Invitation[]};
function MemberCard({member,overview,pending,act}:{member:Member;overview:Overview;pending:boolean;act:(action:string,input:unknown)=>Promise<void>}){
  const [role,setRole]=useState(member.role),manageable=member.role!=='OWNER'&&(overview.role==='OWNER'||member.role!=='ADMIN');
  const owner=overview.members.find(item=>item.userId===overview.userId);
  return <article className="panel"><h3>{member.name}</h3><p>{member.email}</p><p>{labels[member.role]}{member.disabledAt?' · Аккаунт отключён':!member.verifiedAt?' · Email не подтверждён':''}</p>
    {manageable?<div className="studio-actions"><label>Роль<select aria-label={`Роль ${member.email}`} value={role} disabled={pending} onChange={event=>setRole(event.target.value as Role)}>{assignable.filter(value=>overview.role==='OWNER'||value!=='ADMIN').map(value=><option key={value} value={value}>{labels[value]}</option>)}</select></label><button className="button secondary" disabled={pending||role===member.role} onClick={()=>void act('role',{userId:member.userId,revision:member.revision,role})}>Сохранить роль</button><button className="button secondary" disabled={pending} onClick={()=>{if(window.confirm(`Удалить ${member.email} из организации? Доступ к её материалам будет закрыт.`))void act('remove',{userId:member.userId,revision:member.revision});}}>Удалить из команды</button></div>:null}
    {overview.role==='OWNER'&&member.role!=='OWNER'&&member.verifiedAt&&!member.disabledAt&&owner?<button className="button secondary" disabled={pending} onClick={()=>{if(window.confirm(`Передать владение ${member.email}? Вы станете администратором и потеряете доступ к управлению биллингом.`))void act('transfer',{userId:member.userId,revision:member.revision,ownerRevision:owner.revision});}}>Передать владение</button>:null}
  </article>;
}
export function TeamCenter({tenantId}:{tenantId:string}){
  const [overview,setOverview]=useState<Overview|null>(null),[error,setError]=useState(''),[pending,setPending]=useState(false),[email,setEmail]=useState(''),[role,setRole]=useState<Exclude<Role,'OWNER'>>('VIEWER'),[link,setLink]=useState('');
  const intent=useRef<{email:string;role:string;key:string}|null>(null),base=`organizations/${tenantId}/team`;
  const refresh=useCallback(async()=>{setOverview(await api<Overview>(base));},[base]);
  useEffect(()=>{let active=true;api<Overview>(base).then(value=>{if(active)setOverview(value);}).catch(failure=>{if(active)setError(failure instanceof Error?failure.message:'Не удалось загрузить команду');});return()=>{active=false;};},[base]);
  async function act(action:string,input:unknown){setPending(true);setError('');try{await api(`${base}/${action}`,'POST',input);if(action==='revoke'){setLink('');intent.current=null;}if(action==='transfer')setRole('VIEWER');await refresh();}catch(failure){setError(failure instanceof Error?failure.message:'Не удалось изменить команду. Обновите страницу.');}finally{setPending(false);}}
  async function invite(event:FormEvent){event.preventDefault();setPending(true);setError('');setLink('');const normalized=email.trim().toLowerCase();if(!intent.current||intent.current.email!==normalized||intent.current.role!==role)intent.current={email:normalized,role,key:crypto.randomUUID()};try{const result=await api<{link:string}>(`${base}/invite`,'POST',{email:normalized,role,idempotencyKey:intent.current.key});setLink(result.link);await refresh();intent.current=null;}catch(failure){setError(failure instanceof Error?failure.message:'Не удалось создать приглашение');}finally{setPending(false);}}
  async function reload(){setPending(true);setError('');try{await refresh();}catch(failure){setError(failure instanceof Error?failure.message:'Не удалось обновить команду');}finally{setPending(false);}}
  return <main className="workspace-main content-studio team-center"><Link className="back-link" href="/dashboard">← Рабочее пространство</Link><div className="page-title"><div><h1>Команда</h1><p className="muted">Участники и доступ к организации</p></div><button className="button secondary" disabled={pending} onClick={()=>void reload()}>Обновить</button></div>{error?<p className="notice error" role="alert">{error}</p>:null}{!overview&&!error?<p role="status">Загружаем команду…</p>:null}
    {overview?<><section className="panel"><h2>Пригласить участника</h2><form onSubmit={event=>void invite(event)}><label>Email<input type="email" required maxLength={254} value={email} disabled={pending} onChange={event=>{setEmail(event.target.value);setLink('');}}/></label><label>Роль<select value={role} disabled={pending} onChange={event=>{setRole(event.target.value as Exclude<Role,'OWNER'>);setLink('');}}>{assignable.filter(value=>overview.role==='OWNER'||value!=='ADMIN').map(value=><option value={value} key={value}>{labels[value]}</option>)}</select></label><button className="button primary" disabled={pending}>Создать приглашение</button></form><p className="muted">Передайте ссылку участнику самостоятельно. Она работает только с указанным подтверждённым email.</p>{link?<label>Ссылка приглашения<textarea readOnly rows={3} value={link} onFocus={event=>event.target.select()}/></label>:null}</section>
    <section><h2>Участники · {overview.members.length}</h2>{overview.members.map(member=><MemberCard key={`${member.userId}:${member.revision}`} member={member} overview={overview} pending={pending} act={act}/>)}</section><section><h2>Последние приглашения</h2>{!overview.invitations.length?<p>Приглашений пока нет.</p>:null}{overview.invitations.map(item=>{const active=!item.acceptedAt&&!item.revokedAt&&new Date(item.expiresAt)>new Date();return <article className="panel" key={item.id}><h3>{item.email}</h3><p>{labels[item.role]} · {item.acceptedAt?'Принято':item.revokedAt?'Отозвано':active?'Ожидает принятия':'Истекло'}</p><p className="muted">Срок: {new Date(item.expiresAt).toLocaleString('ru-RU')}</p>{!item.acceptedAt&&!item.revokedAt&&(overview.role==='OWNER'||item.role!=='ADMIN')?<button className="button secondary" disabled={pending} onClick={()=>void act('revoke',{id:item.id})}>Отозвать приглашение</button>:null}</article>;})}</section></>:null}
  </main>;
}
