import { AdminService, AgencyService, TeamService, NotificationService, BillingService, PaymentWebhookService, PerformanceService, ChannelAnalyticsService, AnalyticsService, PublishingService, SocialService, credentialVaultFromEnvironment, CalendarService, AuthService, BrandService, GenerationService, ConsentService, MediaService, AvatarService, VoiceService, VideoService } from '@contentos/core';
import { AdminFinanceRepository, AdminRepository, AgencyRepository, TeamRepository, NotificationRepository, BillingRepository, RenewalRepository, PaymentWebhookRepository, PerformanceRepository, ChannelAnalyticsRepository, AnalyticsRepository, PublishingRepository, SocialRepository, CalendarRepository, AuthRepository, BrandRepository, JobRepository, LedgerRepository, ContentRepository, ConsentRepository, MediaRepository, AvatarRepository, VoiceRepository, VideoRepository, createDatabase } from '@contentos/db';
import { parseServerEnvironment } from '@contentos/config';
import { paymentsFromEnvironment, channelAnalyticsFromEnvironment, storageFromEnvironment, avatarFromEnvironment, voiceCatalogFromEnvironment, videoFromEnvironment, captionsFromEnvironment, socialFromEnvironment, publishingFromEnvironment } from '@contentos/providers';
import { DomainError } from '@contentos/types';
function createServices() {
  let env;
  try { env = parseServerEnvironment(process.env); } catch { throw new DomainError('CONFIGURATION_REQUIRED', 503); }
  const { db } = createDatabase(env.DATABASE_URL);
  const emailVault = env.SMTP_URL && env.EMAIL_FROM ? credentialVaultFromEnvironment(env) : null;
  const generation = new GenerationService(new JobRepository(db), new BrandRepository(db), new LedgerRepository(db), new ContentRepository(db), { analyticsAI:env.ANALYTICS_AI_ENABLED==='true', provider: env.AI_PROVIDER, model: env.AI_PROVIDER === 'mock' ? 'mock-v1' : env.OPENAI_MODEL ?? '', ready: env.AI_PROVIDER === 'mock' || (env.AI_PROVIDER === 'openai' && !!env.OPENAI_API_KEY && !!env.OPENAI_MODEL) });
  const storage = storageFromEnvironment(env);
  const paymentProvider=paymentsFromEnvironment(env);
  const paymentMerchant=paymentProvider&&env.YOOKASSA_SHOP_ID?{provider:paymentProvider.name,merchantId:env.YOOKASSA_SHOP_ID,test:env.YOOKASSA_TEST_MODE==='true'}:null;
  const checkoutConfiguration=paymentProvider?.name==='yookassa'&&env.YOOKASSA_SHOP_ID&&env.PAYMENT_RECEIPT_VAT_CODE!==undefined&&env.PAYMENT_RECEIPT_SUBJECT?{merchant:{provider:'yookassa' as const,merchantId:env.YOOKASSA_SHOP_ID,test:env.YOOKASSA_TEST_MODE==='true'},appUrl:env.APP_URL,receipt:{vatCode:Number(env.PAYMENT_RECEIPT_VAT_CODE),...(env.PAYMENT_RECEIPT_TAX_SYSTEM_CODE===undefined?{}:{taxSystemCode:Number(env.PAYMENT_RECEIPT_TAX_SYSTEM_CODE)}),subject:env.PAYMENT_RECEIPT_SUBJECT,mode:'full_payment' as const}}:null;
  return { admin: new AdminService(new AdminRepository(db), env.PLATFORM_ADMIN_ENABLED === 'true', [
    { name: 'AI', provider: env.AI_PROVIDER, model: env.OPENAI_MODEL ?? null, status: env.AI_PROVIDER === 'disabled' ? 'DISABLED' : env.AI_PROVIDER === 'mock' || Boolean(env.OPENAI_API_KEY && env.OPENAI_MODEL) ? 'CONFIGURED' : 'CONFIGURATION_REQUIRED' },
    { name: 'Аватары', provider: env.AVATAR_PROVIDER, model: null, status: env.AVATAR_GENERATION_ENABLED !== 'true' ? 'DISABLED' : avatarFromEnvironment(env) ? 'CONFIGURED' : 'CONFIGURATION_REQUIRED' },
    { name: 'Видео', provider: env.VIDEO_PROVIDER, model: null, status: env.VIDEO_GENERATION_ENABLED !== 'true' ? 'DISABLED' : videoFromEnvironment(env) ? 'CONFIGURED' : 'CONFIGURATION_REQUIRED' },
    { name: 'Хранилище', provider: env.STORAGE_PROVIDER, model: null, status: storage ? 'CONFIGURED' : 'CONFIGURATION_REQUIRED' },
    { name: 'Почта', provider: 'smtp', model: null, status: emailVault ? 'CONFIGURED' : 'CONFIGURATION_REQUIRED' },
    { name: 'Платежи', provider: env.PAYMENT_PROVIDER, model: null, status: env.PAYMENTS_ENABLED !== 'true' ? 'DISABLED' : checkoutConfiguration ? 'CONFIGURED' : 'CONFIGURATION_REQUIRED' },
  ], new AdminFinanceRepository(db)), agency: new AgencyService(new AgencyRepository(db), env.AGENCY_MODE_ENABLED === 'true'), team:new TeamService(new TeamRepository(db),credentialVaultFromEnvironment(env),env.APP_URL), notifications:new NotificationService(new NotificationRepository(db)), billing:new BillingService(new BillingRepository(db),new RenewalRepository(db),checkoutConfiguration,env.PAYMENT_RENEWALS_ENABLED==='true'&&!!credentialVaultFromEnvironment(env)), paymentWebhooks:new PaymentWebhookService(new PaymentWebhookRepository(db),paymentMerchant), env, generation, performance:new PerformanceService(new PerformanceRepository(db),env.ANALYTICS_AI_ENABLED==='true'), channelAnalytics:new ChannelAnalyticsService(new ChannelAnalyticsRepository(db),channelAnalyticsFromEnvironment(env),!!credentialVaultFromEnvironment(env)), analytics:new AnalyticsService(new AnalyticsRepository(db)), publishing:new PublishingService(new PublishingRepository(db),publishingFromEnvironment(env),!!credentialVaultFromEnvironment(env)), social:new SocialService(new SocialRepository(db),socialFromEnvironment(env),credentialVaultFromEnvironment(env)), calendar:new CalendarService(new CalendarRepository(db)), videos:new VideoService(new VideoRepository(db),videoFromEnvironment(env),storage,env.VIDEO_GENERATION_ENABLED==='true',captionsFromEnvironment(env)), voices:new VoiceService(new VoiceRepository(db),voiceCatalogFromEnvironment(env)), avatars: new AvatarService(new AvatarRepository(db), avatarFromEnvironment(env), storage, env.AVATAR_GENERATION_ENABLED==='true'), media: new MediaService(new MediaRepository(db), storage), consent: new ConsentService(new ConsentRepository(db)), auth: new AuthService(new AuthRepository(db), emailVault, env.APP_URL, env.APP_NAME), brands: new BrandService(new BrandRepository(db)) };
}
const globalServices = globalThis as typeof globalThis & { contentosServices?: ReturnType<typeof createServices> };
export function services() { return globalServices.contentosServices ??= createServices(); }
export const sessionCookie = 'contentos_session';
