import {sql} from 'drizzle-orm';
import {pgTable,uuid,text,integer,bigint,jsonb,timestamp,unique,foreignKey,index,check} from 'drizzle-orm/pg-core';
import {brands,users} from './identity';
import {socialConnections} from './social';
import type {ChannelAnalyticsState} from '@contentos/types';
export const channelAnalyticsJobs=pgTable('channel_analytics_jobs',{
  id:uuid('id').primaryKey().defaultRandom(),tenantId:uuid('tenant_id').notNull(),brandId:uuid('brand_id').notNull(),connectionId:uuid('connection_id').notNull(),credentialVersion:integer('credential_version').notNull(),provider:text('provider').notNull(),source:text('source').$type<'API'|'DEMO'>().notNull(),
  type:text('type').notNull().default('FETCH_ANALYTICS'),status:text('status').$type<ChannelAnalyticsState>().notNull().default('QUEUED'),attempt:integer('attempt').notNull().default(0),nextAttemptAt:timestamp('next_attempt_at',{withTimezone:true}).notNull().defaultNow(),dispatchAfter:timestamp('dispatch_after',{withTimezone:true}).notNull().defaultNow(),
  leaseToken:uuid('lease_token'),leaseExpiresAt:timestamp('lease_expires_at',{withTimezone:true}),startedAt:timestamp('started_at',{withTimezone:true}),finishedAt:timestamp('finished_at',{withTimezone:true}),errorCode:text('error_code'),
  idempotencyKey:uuid('idempotency_key').notNull(),requestedBy:uuid('requested_by').notNull().references(()=>users.id),correlationId:uuid('correlation_id').notNull(),createdAt:timestamp('created_at',{withTimezone:true}).notNull().defaultNow(),
},t=>[unique('channel_analytics_tenant_id_uq').on(t.tenantId,t.id),unique('channel_analytics_intent_uq').on(t.tenantId,t.idempotencyKey),foreignKey({columns:[t.tenantId,t.brandId],foreignColumns:[brands.tenantId,brands.id]}),foreignKey({columns:[t.tenantId,t.connectionId],foreignColumns:[socialConnections.tenantId,socialConnections.id]}),index('channel_analytics_due_idx').on(t.status,t.nextAttemptAt,t.dispatchAfter),index('channel_analytics_connection_idx').on(t.tenantId,t.connectionId,t.createdAt),check('channel_analytics_state_valid',sql`${t.status} in ('QUEUED','RUNNING','SUCCEEDED','FAILED','CANCELLED')`),check('channel_analytics_source_valid',sql`${t.source} in ('API','DEMO')`),check('channel_analytics_type_valid',sql`${t.type} = 'FETCH_ANALYTICS'`),check('channel_analytics_attempt_valid',sql`${t.attempt} between 0 and 3 and ${t.credentialVersion} > 0`)]);
export const channelMetrics=pgTable('channel_metrics',{
  id:uuid('id').primaryKey().defaultRandom(),tenantId:uuid('tenant_id').notNull(),connectionId:uuid('connection_id').notNull(),jobId:uuid('job_id').notNull(),provider:text('provider').notNull(),source:text('source').$type<'API'|'DEMO'>().notNull(),memberCount:bigint('member_count',{mode:'number'}).notNull(),observedAt:timestamp('observed_at',{withTimezone:true}).notNull(),recordedAt:timestamp('recorded_at',{withTimezone:true}).notNull().defaultNow(),
},t=>[unique('channel_metrics_tenant_id_uq').on(t.tenantId,t.id),unique('channel_metrics_job_uq').on(t.jobId),foreignKey({columns:[t.tenantId,t.jobId],foreignColumns:[channelAnalyticsJobs.tenantId,channelAnalyticsJobs.id]}),foreignKey({columns:[t.tenantId,t.connectionId],foreignColumns:[socialConnections.tenantId,socialConnections.id]}),index('channel_metrics_history_idx').on(t.tenantId,t.connectionId,t.observedAt),check('channel_metrics_count_valid',sql`${t.memberCount} between 0 and 1000000000000`),check('channel_metrics_source_valid',sql`${t.source} in ('API','DEMO')`)]);
/** Only the numeric API result is retained, never credentials or full response envelopes. */
export const channelMetricEvidence=pgTable('channel_metric_evidence',{
  id:uuid('id').primaryKey().defaultRandom(),tenantId:uuid('tenant_id').notNull(),metricId:uuid('metric_id').notNull(),payload:jsonb('payload').$type<{result:number}>().notNull(),
},t=>[unique('channel_evidence_metric_uq').on(t.metricId),foreignKey({columns:[t.tenantId,t.metricId],foreignColumns:[channelMetrics.tenantId,channelMetrics.id]})]);
